### ISSUE TITLE
非常的好的代码 有更详细的教程吗

### ISSUE THREAD

**Issue by szsyzx** [WeirdoPunk/twitter_spider_to_dingding#2]
非常的好的代码 有更详细的教程吗

请问如何部署在linux系统上啊运行出错
root@vm-standard-a1-flex:~# python3 t.py
t.py:108: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(path, chrome_options=option)
t.py:108: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(path, chrome_options=option)
Traceback (most recent call last):
  File "t.py", line 108, in <module>
    driver = webdriver.Chrome(path, chrome_options=option)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/bin/chromedriver'

**Comment by szsyzx** [comment]
老大求助啊看到消息能回复下吗 万分感谢
